// This file is auto-generated by @hey-api/openapi-ts

export const UpdatePlayerRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        roles: {
            type: 'array',
            items: {
                type: 'string',
                enum: [
                    'R4',
                    'Central',
                    'Passeur',
                    'Pointu',
                    'Libero'
                ]
            }
        },
        numero: {
            type: 'integer',
            format: 'int32'
        },
        age: {
            type: 'integer',
            format: 'int32'
        },
        taille: {
            type: 'string'
        },
        teamIds: {
            type: 'array',
            items: {
                type: 'integer',
                format: 'int64'
            }
        }
    }
} as const;

export const ApiResponsePlayerDtoSchema = {
    type: 'object',
    properties: {
        data: {
            $ref: '#/components/schemas/PlayerDto'
        },
        message: {
            type: 'string'
        },
        status: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const PlayerDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        name: {
            type: 'string'
        },
        roles: {
            type: 'array',
            items: {
                type: 'string',
                enum: [
                    'R4',
                    'Central',
                    'Passeur',
                    'Pointu',
                    'Libero'
                ]
            }
        },
        numero: {
            type: 'integer',
            format: 'int32'
        },
        age: {
            type: 'integer',
            format: 'int32'
        },
        taille: {
            type: 'string'
        },
        teamIds: {
            type: 'array',
            items: {
                type: 'integer',
                format: 'int64'
            }
        }
    }
} as const;

export const CreateTeamRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        city: {
            type: 'string'
        },
        logoColor: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseTeamDtoSchema = {
    type: 'object',
    properties: {
        data: {
            $ref: '#/components/schemas/TeamDto'
        },
        message: {
            type: 'string'
        },
        status: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const TeamDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        name: {
            type: 'string'
        },
        city: {
            type: 'string'
        },
        logoColor: {
            type: 'string'
        },
        players: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TeamPlayerDto'
            }
        }
    }
} as const;

export const TeamPlayerDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        name: {
            type: 'string'
        },
        roles: {
            type: 'array',
            items: {
                type: 'string',
                enum: [
                    'R4',
                    'Central',
                    'Passeur',
                    'Pointu',
                    'Libero'
                ]
            }
        },
        numero: {
            type: 'integer',
            format: 'int32'
        },
        age: {
            type: 'integer',
            format: 'int32'
        },
        taille: {
            type: 'string'
        }
    }
} as const;

export const RemovePlayersRequestSchema = {
    type: 'object',
    properties: {
        playerIds: {
            type: 'array',
            items: {
                type: 'integer',
                format: 'int64'
            }
        }
    }
} as const;

export const AssignPlayersRequestSchema = {
    type: 'object',
    properties: {
        playerIds: {
            type: 'array',
            items: {
                type: 'integer',
                format: 'int64'
            }
        }
    }
} as const;

export const CreatePlayerRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        roles: {
            type: 'array',
            items: {
                type: 'string',
                enum: [
                    'R4',
                    'Central',
                    'Passeur',
                    'Pointu',
                    'Libero'
                ]
            }
        },
        numero: {
            type: 'integer',
            format: 'int32'
        },
        age: {
            type: 'integer',
            format: 'int32'
        },
        taille: {
            type: 'string'
        },
        teamIds: {
            type: 'array',
            items: {
                type: 'integer',
                format: 'int64'
            }
        }
    }
} as const;

export const MatchDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        teamId: {
            type: 'integer',
            format: 'int64'
        },
        opponentId: {
            type: 'integer',
            format: 'int64'
        },
        seasonId: {
            type: 'string'
        },
        competitionId: {
            type: 'integer',
            format: 'int64'
        },
        title: {
            type: 'string'
        },
        home: {
            type: 'boolean'
        },
        date: {
            type: 'string',
            format: 'date'
        },
        result: {
            type: 'string'
        },
        mySets: {
            type: 'integer',
            format: 'int32'
        },
        oppSets: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const MatchStatRequestSchema = {
    type: 'object',
    properties: {
        match: {
            $ref: '#/components/schemas/MatchDto'
        },
        sets: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/SetStatDto'
            }
        },
        players: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PlayerStatDto'
            }
        },
        teamMatchStats: {
            $ref: '#/components/schemas/StatsDto'
        },
        meta: {
            $ref: '#/components/schemas/MetaDto'
        }
    }
} as const;

export const MetaDtoSchema = {
    type: 'object',
    properties: {
        clientGeneratedAt: {
            type: 'string',
            format: 'date-time'
        },
        appVersion: {
            type: 'string'
        }
    }
} as const;

export const PlayerSetStatDtoSchema = {
    type: 'object',
    properties: {
        set: {
            type: 'integer',
            format: 'int32'
        },
        position: {
            type: 'string'
        },
        points: {
            type: 'integer',
            format: 'int32'
        },
        attackPoints: {
            type: 'integer',
            format: 'int32'
        },
        blockPoints: {
            type: 'integer',
            format: 'int32'
        },
        acePoints: {
            type: 'integer',
            format: 'int32'
        },
        attackErrors: {
            type: 'integer',
            format: 'int32'
        },
        serviceErrors: {
            type: 'integer',
            format: 'int32'
        },
        receptions: {
            type: 'integer',
            format: 'int32'
        },
        faults: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const PlayerStatDtoSchema = {
    type: 'object',
    properties: {
        playerId: {
            type: 'integer',
            format: 'int64'
        },
        number: {
            type: 'integer',
            format: 'int32'
        },
        role: {
            type: 'string',
            enum: [
                'R4',
                'Central',
                'Passeur',
                'Pointu',
                'Libero'
            ]
        },
        matchStats: {
            $ref: '#/components/schemas/StatsDto'
        },
        setStats: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PlayerSetStatDto'
            }
        }
    }
} as const;

export const SetStatDtoSchema = {
    type: 'object',
    properties: {
        set: {
            type: 'integer',
            format: 'int32'
        },
        myScore: {
            type: 'integer',
            format: 'int32'
        },
        oppScore: {
            type: 'integer',
            format: 'int32'
        },
        teamStats: {
            $ref: '#/components/schemas/StatsDto'
        },
        timeline: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TimelineEntryDto'
            }
        }
    }
} as const;

export const StatsDtoSchema = {
    type: 'object',
    properties: {
        points: {
            type: 'integer',
            format: 'int32'
        },
        attackPoints: {
            type: 'integer',
            format: 'int32'
        },
        blockPoints: {
            type: 'integer',
            format: 'int32'
        },
        acePoints: {
            type: 'integer',
            format: 'int32'
        },
        attackErrors: {
            type: 'integer',
            format: 'int32'
        },
        serviceErrors: {
            type: 'integer',
            format: 'int32'
        },
        receptions: {
            type: 'integer',
            format: 'int32'
        },
        faults: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const TimelineEntryDtoSchema = {
    type: 'object',
    properties: {
        myScore: {
            type: 'integer',
            format: 'int32'
        },
        oppScore: {
            type: 'integer',
            format: 'int32'
        },
        playerId: {
            type: 'integer',
            format: 'int64'
        },
        action: {
            type: 'string'
        },
        occurredAt: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const ApiResponseMatchStatResponseSchema = {
    type: 'object',
    properties: {
        data: {
            $ref: '#/components/schemas/MatchStatResponse'
        },
        message: {
            type: 'string'
        },
        status: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const MatchStatResponseSchema = {
    type: 'object',
    properties: {
        matchId: {
            type: 'string'
        }
    }
} as const;

export const RegisterRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        pseudo: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseUserResponseSchema = {
    type: 'object',
    properties: {
        data: {
            $ref: '#/components/schemas/UserResponse'
        },
        message: {
            type: 'string'
        },
        status: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const UserResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        email: {
            type: 'string'
        },
        pseudo: {
            type: 'string'
        }
    }
} as const;

export const RefreshRequestSchema = {
    type: 'object',
    properties: {
        refreshToken: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseAuthResponseSchema = {
    type: 'object',
    properties: {
        data: {
            $ref: '#/components/schemas/AuthResponse'
        },
        message: {
            type: 'string'
        },
        status: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const AuthResponseSchema = {
    type: 'object',
    properties: {
        accessToken: {
            type: 'string'
        },
        refreshToken: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseVoidSchema = {
    type: 'object',
    properties: {
        data: {},
        message: {
            type: 'string'
        },
        status: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const LoginRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseListTeamDtoSchema = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/TeamDto'
            }
        },
        message: {
            type: 'string'
        },
        status: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const ApiResponseListMatchDtoSchema = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/MatchDto'
            }
        },
        message: {
            type: 'string'
        },
        status: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const ApiResponseListPlayerDtoSchema = {
    type: 'object',
    properties: {
        data: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PlayerDto'
            }
        },
        message: {
            type: 'string'
        },
        status: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const ApiResponsePlayerSeasonStatsResponseSchema = {
    type: 'object',
    properties: {
        data: {
            $ref: '#/components/schemas/PlayerSeasonStatsResponse'
        },
        message: {
            type: 'string'
        },
        status: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const PlayerSeasonStatsResponseSchema = {
    type: 'object',
    properties: {
        playerId: {
            type: 'integer',
            format: 'int64'
        },
        matchCount: {
            type: 'integer',
            format: 'int32'
        },
        setCount: {
            type: 'integer',
            format: 'int32'
        },
        totalStats: {
            $ref: '#/components/schemas/StatsDto'
        },
        statsByPosition: {
            type: 'object',
            additionalProperties: {
                $ref: '#/components/schemas/PositionStatsDto'
            }
        }
    }
} as const;

export const PositionStatsDtoSchema = {
    type: 'object',
    properties: {
        matchCount: {
            type: 'integer',
            format: 'int32'
        },
        setCount: {
            type: 'integer',
            format: 'int32'
        },
        stats: {
            $ref: '#/components/schemas/StatsDto'
        }
    }
} as const;

export const ApiResponseMatchDetailResponseSchema = {
    type: 'object',
    properties: {
        data: {
            $ref: '#/components/schemas/MatchDetailResponse'
        },
        message: {
            type: 'string'
        },
        status: {
            type: 'integer',
            format: 'int32'
        }
    }
} as const;

export const MatchDetailResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        teamId: {
            type: 'integer',
            format: 'int64'
        },
        opponentId: {
            type: 'integer',
            format: 'int64'
        },
        seasonId: {
            type: 'string'
        },
        competitionId: {
            type: 'integer',
            format: 'int64'
        },
        title: {
            type: 'string'
        },
        home: {
            type: 'boolean'
        },
        date: {
            type: 'string',
            format: 'date'
        },
        result: {
            type: 'string'
        },
        mySets: {
            type: 'integer',
            format: 'int32'
        },
        oppSets: {
            type: 'integer',
            format: 'int32'
        },
        teamMatchStats: {
            $ref: '#/components/schemas/StatsDto'
        },
        sets: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/SetStatDto'
            }
        },
        players: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/PlayerStatDto'
            }
        }
    }
} as const;
