// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AssignPlayersData, AssignPlayersResponses, CreatePlayerData, CreatePlayerResponses, CreateTeamData, CreateTeamResponses, DeletePlayerData, DeletePlayerResponses, GetAllPlayersData, GetAllPlayersResponses, GetAllTeamsData, GetAllTeamsResponses, GetMatchStatData, GetMatchStatResponses, GetPlayerData, GetPlayerResponses, GetPlayerSeasonStatsData, GetPlayerSeasonStatsResponses, GetTeamData, GetTeamMatchesData, GetTeamMatchesResponses, GetTeamResponses, LoginData, LoginResponses, LogoutData, LogoutResponses, RefreshData, RefreshResponses, RegisterData, RegisterResponses, RemovePlayersData, RemovePlayersResponses, SaveMatchStatData, SaveMatchStatResponses, UpdatePlayerData, UpdatePlayerResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const deletePlayer = <ThrowOnError extends boolean = false>(options: Options<DeletePlayerData, ThrowOnError>) => (options.client ?? client).delete<DeletePlayerResponses, unknown, ThrowOnError>({ url: '/api/v1/players/{id}', ...options });

export const getPlayer = <ThrowOnError extends boolean = false>(options: Options<GetPlayerData, ThrowOnError>) => (options.client ?? client).get<GetPlayerResponses, unknown, ThrowOnError>({ url: '/api/v1/players/{id}', ...options });

export const updatePlayer = <ThrowOnError extends boolean = false>(options: Options<UpdatePlayerData, ThrowOnError>) => (options.client ?? client).put<UpdatePlayerResponses, unknown, ThrowOnError>({
    url: '/api/v1/players/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAllTeams = <ThrowOnError extends boolean = false>(options?: Options<GetAllTeamsData, ThrowOnError>) => (options?.client ?? client).get<GetAllTeamsResponses, unknown, ThrowOnError>({ url: '/api/v1/teams', ...options });

export const createTeam = <ThrowOnError extends boolean = false>(options: Options<CreateTeamData, ThrowOnError>) => (options.client ?? client).post<CreateTeamResponses, unknown, ThrowOnError>({
    url: '/api/v1/teams',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const removePlayers = <ThrowOnError extends boolean = false>(options: Options<RemovePlayersData, ThrowOnError>) => (options.client ?? client).post<RemovePlayersResponses, unknown, ThrowOnError>({
    url: '/api/v1/teams/{id}:removePlayers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const assignPlayers = <ThrowOnError extends boolean = false>(options: Options<AssignPlayersData, ThrowOnError>) => (options.client ?? client).post<AssignPlayersResponses, unknown, ThrowOnError>({
    url: '/api/v1/teams/{id}:assignPlayers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getAllPlayers = <ThrowOnError extends boolean = false>(options?: Options<GetAllPlayersData, ThrowOnError>) => (options?.client ?? client).get<GetAllPlayersResponses, unknown, ThrowOnError>({ url: '/api/v1/players', ...options });

export const createPlayer = <ThrowOnError extends boolean = false>(options: Options<CreatePlayerData, ThrowOnError>) => (options.client ?? client).post<CreatePlayerResponses, unknown, ThrowOnError>({
    url: '/api/v1/players',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const saveMatchStat = <ThrowOnError extends boolean = false>(options: Options<SaveMatchStatData, ThrowOnError>) => (options.client ?? client).post<SaveMatchStatResponses, unknown, ThrowOnError>({
    url: '/api/v1/match-stats',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const register = <ThrowOnError extends boolean = false>(options: Options<RegisterData, ThrowOnError>) => (options.client ?? client).post<RegisterResponses, unknown, ThrowOnError>({
    url: '/api/v1/auth:register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const refresh = <ThrowOnError extends boolean = false>(options: Options<RefreshData, ThrowOnError>) => (options.client ?? client).post<RefreshResponses, unknown, ThrowOnError>({
    url: '/api/v1/auth:refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const logout = <ThrowOnError extends boolean = false>(options: Options<LogoutData, ThrowOnError>) => (options.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
    url: '/api/v1/auth:logout',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
    url: '/api/v1/auth:login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getTeam = <ThrowOnError extends boolean = false>(options: Options<GetTeamData, ThrowOnError>) => (options.client ?? client).get<GetTeamResponses, unknown, ThrowOnError>({ url: '/api/v1/teams/{id}', ...options });

export const getTeamMatches = <ThrowOnError extends boolean = false>(options: Options<GetTeamMatchesData, ThrowOnError>) => (options.client ?? client).get<GetTeamMatchesResponses, unknown, ThrowOnError>({ url: '/api/v1/teams/{id}/matches', ...options });

export const getPlayerSeasonStats = <ThrowOnError extends boolean = false>(options: Options<GetPlayerSeasonStatsData, ThrowOnError>) => (options.client ?? client).get<GetPlayerSeasonStatsResponses, unknown, ThrowOnError>({ url: '/api/v1/players/{id}/season-stats', ...options });

export const getMatchStat = <ThrowOnError extends boolean = false>(options: Options<GetMatchStatData, ThrowOnError>) => (options.client ?? client).get<GetMatchStatResponses, unknown, ThrowOnError>({ url: '/api/v1/match-stats/{matchId}', ...options });
