// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type UpdatePlayerRequest = {
    name?: string;
    roles?: Array<'R4' | 'Central' | 'Passeur' | 'Pointu' | 'Libero'>;
    numero?: number;
    age?: number;
    taille?: string;
    teamIds?: Array<number>;
};

export type ApiResponsePlayerDto = {
    data?: PlayerDto;
    message?: string;
    status?: number;
};

export type PlayerDto = {
    id?: number;
    name?: string;
    roles?: Array<'R4' | 'Central' | 'Passeur' | 'Pointu' | 'Libero'>;
    numero?: number;
    age?: number;
    taille?: string;
    teamIds?: Array<number>;
};

export type CreateTeamRequest = {
    name?: string;
    city?: string;
    logoColor?: string;
};

export type ApiResponseTeamDto = {
    data?: TeamDto;
    message?: string;
    status?: number;
};

export type TeamDto = {
    id?: number;
    name?: string;
    city?: string;
    logoColor?: string;
    players?: Array<TeamPlayerDto>;
};

export type TeamPlayerDto = {
    id?: number;
    name?: string;
    roles?: Array<'R4' | 'Central' | 'Passeur' | 'Pointu' | 'Libero'>;
    numero?: number;
    age?: number;
    taille?: string;
};

export type RemovePlayersRequest = {
    playerIds?: Array<number>;
};

export type AssignPlayersRequest = {
    playerIds?: Array<number>;
};

export type CreatePlayerRequest = {
    name?: string;
    roles?: Array<'R4' | 'Central' | 'Passeur' | 'Pointu' | 'Libero'>;
    numero?: number;
    age?: number;
    taille?: string;
    teamIds?: Array<number>;
};

export type MatchDto = {
    id?: string;
    teamId?: number;
    opponentId?: number;
    seasonId?: string;
    competitionId?: number;
    title?: string;
    home?: boolean;
    date?: string;
    result?: string;
    mySets?: number;
    oppSets?: number;
};

export type MatchStatRequest = {
    match?: MatchDto;
    sets?: Array<SetStatDto>;
    players?: Array<PlayerStatDto>;
    teamMatchStats?: StatsDto;
    meta?: MetaDto;
};

export type MetaDto = {
    clientGeneratedAt?: string;
    appVersion?: string;
};

export type PlayerSetStatDto = {
    set?: number;
    position?: string;
    points?: number;
    attackPoints?: number;
    blockPoints?: number;
    acePoints?: number;
    attackErrors?: number;
    serviceErrors?: number;
    receptions?: number;
    faults?: number;
};

export type PlayerStatDto = {
    playerId?: number;
    number?: number;
    role?: 'R4' | 'Central' | 'Passeur' | 'Pointu' | 'Libero';
    matchStats?: StatsDto;
    setStats?: Array<PlayerSetStatDto>;
};

export type SetStatDto = {
    set?: number;
    myScore?: number;
    oppScore?: number;
    teamStats?: StatsDto;
    timeline?: Array<TimelineEntryDto>;
};

export type StatsDto = {
    points?: number;
    attackPoints?: number;
    blockPoints?: number;
    acePoints?: number;
    attackErrors?: number;
    serviceErrors?: number;
    receptions?: number;
    faults?: number;
};

export type TimelineEntryDto = {
    myScore?: number;
    oppScore?: number;
    playerId?: number;
    action?: string;
    occurredAt?: string;
};

export type ApiResponseMatchStatResponse = {
    data?: MatchStatResponse;
    message?: string;
    status?: number;
};

export type MatchStatResponse = {
    matchId?: string;
};

export type RegisterRequest = {
    email?: string;
    pseudo?: string;
    password?: string;
};

export type ApiResponseUserResponse = {
    data?: UserResponse;
    message?: string;
    status?: number;
};

export type UserResponse = {
    id?: string;
    email?: string;
    pseudo?: string;
};

export type RefreshRequest = {
    refreshToken?: string;
};

export type ApiResponseAuthResponse = {
    data?: AuthResponse;
    message?: string;
    status?: number;
};

export type AuthResponse = {
    accessToken?: string;
    refreshToken?: string;
};

export type ApiResponseVoid = {
    data?: unknown;
    message?: string;
    status?: number;
};

export type LoginRequest = {
    email?: string;
    password?: string;
};

export type ApiResponseListTeamDto = {
    data?: Array<TeamDto>;
    message?: string;
    status?: number;
};

export type ApiResponseListMatchDto = {
    data?: Array<MatchDto>;
    message?: string;
    status?: number;
};

export type ApiResponseListPlayerDto = {
    data?: Array<PlayerDto>;
    message?: string;
    status?: number;
};

export type ApiResponsePlayerSeasonStatsResponse = {
    data?: PlayerSeasonStatsResponse;
    message?: string;
    status?: number;
};

export type PlayerSeasonStatsResponse = {
    playerId?: number;
    matchCount?: number;
    setCount?: number;
    totalStats?: StatsDto;
    statsByPosition?: {
        [key: string]: PositionStatsDto;
    };
};

export type PositionStatsDto = {
    matchCount?: number;
    setCount?: number;
    stats?: StatsDto;
};

export type ApiResponseMatchDetailResponse = {
    data?: MatchDetailResponse;
    message?: string;
    status?: number;
};

export type MatchDetailResponse = {
    id?: string;
    teamId?: number;
    opponentId?: number;
    seasonId?: string;
    competitionId?: number;
    title?: string;
    home?: boolean;
    date?: string;
    result?: string;
    mySets?: number;
    oppSets?: number;
    teamMatchStats?: StatsDto;
    sets?: Array<SetStatDto>;
    players?: Array<PlayerStatDto>;
};

export type DeletePlayerData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/players/{id}';
};

export type DeletePlayerResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type DeletePlayerResponse = DeletePlayerResponses[keyof DeletePlayerResponses];

export type GetPlayerData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/players/{id}';
};

export type GetPlayerResponses = {
    /**
     * OK
     */
    200: ApiResponsePlayerDto;
};

export type GetPlayerResponse = GetPlayerResponses[keyof GetPlayerResponses];

export type UpdatePlayerData = {
    body: UpdatePlayerRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/players/{id}';
};

export type UpdatePlayerResponses = {
    /**
     * OK
     */
    200: ApiResponsePlayerDto;
};

export type UpdatePlayerResponse = UpdatePlayerResponses[keyof UpdatePlayerResponses];

export type GetAllTeamsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/teams';
};

export type GetAllTeamsResponses = {
    /**
     * OK
     */
    200: ApiResponseListTeamDto;
};

export type GetAllTeamsResponse = GetAllTeamsResponses[keyof GetAllTeamsResponses];

export type CreateTeamData = {
    body: CreateTeamRequest;
    path?: never;
    query?: never;
    url: '/api/v1/teams';
};

export type CreateTeamResponses = {
    /**
     * OK
     */
    200: ApiResponseTeamDto;
};

export type CreateTeamResponse = CreateTeamResponses[keyof CreateTeamResponses];

export type RemovePlayersData = {
    body: RemovePlayersRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/teams/{id}:removePlayers';
};

export type RemovePlayersResponses = {
    /**
     * OK
     */
    200: ApiResponseTeamDto;
};

export type RemovePlayersResponse = RemovePlayersResponses[keyof RemovePlayersResponses];

export type AssignPlayersData = {
    body: AssignPlayersRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/teams/{id}:assignPlayers';
};

export type AssignPlayersResponses = {
    /**
     * OK
     */
    200: ApiResponseTeamDto;
};

export type AssignPlayersResponse = AssignPlayersResponses[keyof AssignPlayersResponses];

export type GetAllPlayersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/players';
};

export type GetAllPlayersResponses = {
    /**
     * OK
     */
    200: ApiResponseListPlayerDto;
};

export type GetAllPlayersResponse = GetAllPlayersResponses[keyof GetAllPlayersResponses];

export type CreatePlayerData = {
    body: CreatePlayerRequest;
    path?: never;
    query?: never;
    url: '/api/v1/players';
};

export type CreatePlayerResponses = {
    /**
     * OK
     */
    200: ApiResponsePlayerDto;
};

export type CreatePlayerResponse = CreatePlayerResponses[keyof CreatePlayerResponses];

export type SaveMatchStatData = {
    body: MatchStatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/match-stats';
};

export type SaveMatchStatResponses = {
    /**
     * OK
     */
    200: ApiResponseMatchStatResponse;
};

export type SaveMatchStatResponse = SaveMatchStatResponses[keyof SaveMatchStatResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth:register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: ApiResponseUserResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type RefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth:refresh';
};

export type RefreshResponses = {
    /**
     * OK
     */
    200: ApiResponseAuthResponse;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LogoutData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth:logout';
};

export type LogoutResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth:login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: ApiResponseAuthResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type GetTeamData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/teams/{id}';
};

export type GetTeamResponses = {
    /**
     * OK
     */
    200: ApiResponseTeamDto;
};

export type GetTeamResponse = GetTeamResponses[keyof GetTeamResponses];

export type GetTeamMatchesData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/teams/{id}/matches';
};

export type GetTeamMatchesResponses = {
    /**
     * OK
     */
    200: ApiResponseListMatchDto;
};

export type GetTeamMatchesResponse = GetTeamMatchesResponses[keyof GetTeamMatchesResponses];

export type GetPlayerSeasonStatsData = {
    body?: never;
    path: {
        id: number;
    };
    query: {
        teamId: number;
    };
    url: '/api/v1/players/{id}/season-stats';
};

export type GetPlayerSeasonStatsResponses = {
    /**
     * OK
     */
    200: ApiResponsePlayerSeasonStatsResponse;
};

export type GetPlayerSeasonStatsResponse = GetPlayerSeasonStatsResponses[keyof GetPlayerSeasonStatsResponses];

export type GetMatchStatData = {
    body?: never;
    path: {
        matchId: string;
    };
    query?: never;
    url: '/api/v1/match-stats/{matchId}';
};

export type GetMatchStatResponses = {
    /**
     * OK
     */
    200: ApiResponseMatchDetailResponse;
};

export type GetMatchStatResponse = GetMatchStatResponses[keyof GetMatchStatResponses];
